// <auto-generated />
using System;
using IME.SpotDataApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IME.SpotDataApi.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250727155506_keyless")]
    partial class keyless
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("IME.SpotDataApi.Models.Notification.NewsNotification", b =>
                {
                    b.Property<string>("Body")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstPicture")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NewsDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("PriorTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortAbstract")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.ToTable("NewsNotifications");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Notification.SpotNotification", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NewsDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.ToTable("SpotNotifications");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Public.Broker", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.BuyMethod", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BuyMethods");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Commodity", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Commodities");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.ContractType", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("ContractTypes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.CurrencyUnit", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CurrencyUnits");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.DeliveryPlace", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("DeliveryPlaces");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Group", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.MainGroup", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MainGroups");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Manufacturer", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.MeasurementUnit", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("MeasurementUnits");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Offer", b =>
                {
                    b.Property<int>("BrokerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyMethodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommodityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InitVolume")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LotSize")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxIncOfferVol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxInitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxOfferPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxOrderVol")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeasureUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinAllocationVol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinInitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinOfferPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinOfferVol")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinOrderVol")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferModeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferRing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OfferVol")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackagingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PermissibleError")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrepaymentPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceDiscoveryMinOrderVol")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityTypeNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SettlementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TickSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TradingHallId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightFactor")
                        .HasColumnType("TEXT");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.OfferMode", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("OfferModes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.OfferType", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("OfferTypes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.PackagingType", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("PackagingTypes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.SecurityType", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SecurityTypes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.SettlementType", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SettlementTypes");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.SubGroup", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("SubGroups");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Supplier", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NationalCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.Tender", b =>
                {
                    b.Property<int>("BrokerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommodityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryPlaceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InitPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LoadFactor")
                        .HasColumnType("TEXT");

                    b.Property<int>("LotCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LotSize")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxBuyPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxIncreaseDemand")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxSellPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinBuyPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinSellPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackagingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettlementTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TenderApplicantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenderDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Tenders");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.TradeReport", b =>
                {
                    b.Property<string>("BuyMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CommodityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContractTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DemandVolume")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalWeightedAveragePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaximumPrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeasurementUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimumPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OfferBasePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("OfferId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OfferMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfferType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OfferVolume")
                        .HasColumnType("TEXT");

                    b.Property<int>("SellerBrokerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TradeDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradeValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TradeVolume")
                        .HasColumnType("TEXT");

                    b.ToTable("TradeReports");
                });

            modelBuilder.Entity("IME.SpotDataApi.Models.Spot.TradingHall", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("TradingHalls");
                });
#pragma warning restore 612, 618
        }
    }
}
