//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IME.SpotDataApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IME.MobileApp.Shared.Resources.NotificationIcons", typeof(NotificationIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M15.7162 16.2234H8.4962&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M15.7162 12.0369H8.4962&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M11.2513 7.86011H8.4963&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path fill-rule=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ابلاغیه {
            get {
                return ResourceManager.GetString("ابلاغیه", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M11.4923 2.78894H7.7533C4.6783 2.78894 2.75031 4.96594 2.75031 8.04794V16.3619C2.75031 19.4439 4.6693 21.6209 7.7533 21.6209H16.5773C19.6623 21.6209 21.5813 19.4439 21.5813 16.3619V12.3339&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path fill-rule=&quot;evenodd&quot; clip-rule=&quot;evenodd&quot; d=&quot;M8.8278 10.9209L16.3008 3.44787C17.2318 2.51787 18.7408 2.51787 19.67 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string اصلاحیه {
            get {
                return ResourceManager.GetString("اصلاحیه", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;path fill-rule=&quot;evenodd&quot; clip-rule=&quot;evenodd&quot; d=&quot;M14.7363 2.76196H8.08431C6.02531 2.76196 4.25031 4.43096 4.25031 6.49096V17.34C4.25031 19.516 5.90831 21.115 8.08431 21.115H16.0723C18.1323 21.115 19.8023 19.4 19.8023 17.34V8.03796L14.7363 2.76196Z&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path d=&quot;M14.4736 2.75024V5.65924C14.4736 7.07924 15.6226 8.23124 17.0426 8.23424C [rest of string was truncated]&quot;;.
        /// </summary>
        public static string پذیرش_کالا {
            get {
                return ResourceManager.GetString("پذیرش کالا", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M11.9899 15.7962V11.3772&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path opacity=&quot;0.4&quot; d=&quot;M11.9899 8.20435H11.9999&quot; stroke=&quot;#200E32&quot; stroke-width=&quot;1.5&quot; stroke-linecap=&quot;round&quot; stroke-linejoin=&quot;round&quot;/&gt;
        ///&lt;path fill-rule=&quot;evenodd&quot; clip-rule=&quot;evenodd&quot; d=&quot;M16.3346 2.75024H7.66561C4.64461 2.75024 2.75061 4.88924 2.75061 7.91624V16.0842C2.75061 19.1112 4. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string پیش_فرض {
            get {
                return ResourceManager.GetString("پیش فرض", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;svg width=&quot;24&quot; height=&quot;24&quot; viewBox=&quot;0 0 24 24&quot; fill=&quot;none&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;path fill-rule=&quot;evenodd&quot; clip-rule=&quot;evenodd&quot; d=&quot;M18.865 5.12377C19.302 5.27677 19.594 5.68877 19.594 6.15177V12.9248C19.594 14.8178 18.906 16.6248 17.691 18.0248C17.08 18.7298 16.307 19.2788 15.486 19.7228L11.928 21.6448L8.364 19.7218C7.542 19.2778 6.768 18.7298 6.156 18.0238C4.94 16.6238 4.25 14.8158 4.25 12.9208V6.15177C4.25 5.68877 4.542 5.27677 4.979 5.12377L11.561 2.81077C11.795 2.72877 12.05 2.72877 12.283 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string تمدید_مجوز {
            get {
                return ResourceManager.GetString("تمدید مجوز", resourceCulture);
            }
        }
    }
}
