//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IME.SpotDataApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RingIcons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RingIcons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IME.MobileApp.Shared.Resources.RingIcons", typeof(RingIcons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petrochemical.
        /// </summary>
        public static string تالار_پتروشیمی {
            get {
                return ResourceManager.GetString("تالار پتروشیمی", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open-auction.
        /// </summary>
        public static string تالار_حراج_باز {
            get {
                return ResourceManager.GetString("تالار حراج باز", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.
        /// </summary>
        public static string تالار_خودرو {
            get {
                return ResourceManager.GetString("تالار خودرو", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cement.
        /// </summary>
        public static string تالار_سیمان {
            get {
                return ResourceManager.GetString("تالار سیمان", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to industrial.
        /// </summary>
        public static string تالار_صنعتی {
            get {
                return ResourceManager.GetString("تالار صنعتی", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petroleum.
        /// </summary>
        public static string تالار_فرآورده_های_نفتی {
            get {
                return ResourceManager.GetString("تالار فرآورده های نفتی", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to substitute.
        /// </summary>
        public static string تالار_فرعی {
            get {
                return ResourceManager.GetString("تالار فرعی", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export-goods.
        /// </summary>
        public static string تالار_کالای_صادراتی_کيش {
            get {
                return ResourceManager.GetString("تالار کالای صادراتی کيش", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agriculture.
        /// </summary>
        public static string تالار_کشاورزی {
            get {
                return ResourceManager.GetString("تالار کشاورزی", resourceCulture);
            }
        }
    }
}
